"""
API 리스트 생성기
FastAPI 소스 코드를 스캔하여 요약된 API 목록을 테이블 형태로 생성합니다.
"""

import os
import re
from datetime import datetime

def generate_api_list_docs(root_dir, output_dir):
    """API 리스트 문서 생성"""
    
    output_file = os.path.join(output_dir, "API_LIST.md")
    main_py = os.path.join(root_dir, "src", "main.py")
    
    if not os.path.exists(main_py):
        return {'error': 'main.py not found'}

    routes = []
    
    # src 디렉토리 내의 모든 파이썬 파일 스캔 (라우터 포함)
    src_dir = os.path.join(root_dir, "src")
    for root, _, files in os.walk(src_dir):
        for file in files:
            if file.endswith(".py"):
                file_path = os.path.join(root, file)
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                # 라우트 패턴 검색 (router.get, app.get 등)
                # 예: @router.get("/users", tags=["Users"])
                route_pattern = r'@(?:app|router)\.(get|post|put|delete|patch)\s*\(\s*["\']([^"\']+)["\']'
                
                matches = list(re.finditer(route_pattern, content))
                
                for match in matches:
                    method = match.group(1).upper()
                    path = match.group(2)
                    
                    # 함수 정의 찾기 (데코레이터 바로 아래)
                    func_start = match.end()
                    func_match = re.search(r'def\s+(\w+)\s*\(', content[func_start:func_start+500])
                    
                    if func_match:
                        func_name = func_match.group(1)
                        
                        # Docstring 찾기
                        docstring_match = re.search(
                            r'def\s+'+func_name+r'\s*\([^)]*\):\s*(?:[^:]*:\s*)?"""([^"]+)"""', 
                            content[func_start:func_start+1000], 
                            re.DOTALL
                        )
                        
                        description = ""
                        if docstring_match:
                            description = docstring_match.group(1).strip().split('\n')[0] # 첫 줄만 사용
                        else:
                            description = func_name.replace('_', ' ').capitalize()
                            
                        routes.append({
                            'method': method,
                            'path': path,
                            'function': func_name,
                            'description': description,
                            'file': os.path.relpath(file_path, root_dir)
                        })

    # 경로 기준으로 정렬
    routes.sort(key=lambda x: (x['path'], x['method']))

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 📋 API List\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"> **Total APIs:** {len(routes)}\n\n")
        
        f.write("| Method | Path | Function | Description | Source |\n")
        f.write("|:---:|:---|:---|:---|:---|\n")
        
        for route in routes:
            method_badge = ""
            if route['method'] == 'GET':
                method_badge = "🔵 GET"
            elif route['method'] == 'POST':
                method_badge = "🟢 POST"
            elif route['method'] == 'PUT':
                method_badge = "🟠 PUT"
            elif route['method'] == 'DELETE':
                method_badge = "🔴 DEL"
            else:
                method_badge = f"⚪ {route['method']}"
                
            f.write(f"| {method_badge} | `{route['path']}` | `{route['function']}` | {route['description']} | `{route['file']}` |\n")
            
        f.write("\n")
        f.write("*Generated by Monewment Auto-Doc System v5.0*\n")
        
    return {
        'file': output_file,
        'count': len(routes)
    }
