"""
API 문서 생성기
완전한 API 레퍼런스 문서를 요청/응답 예제와 함께 생성합니다.
"""

import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.collector import collector

def generate_api_docs(root_dir, output_dir):
    """API 레퍼런스 문서 생성"""
    
    # API 엔드포인트 수집
    api_list = collector.collect_api_endpoints()
    
    # 문서 작성
    output_file = os.path.join(output_dir, "API_REFERENCE.md")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 📡 Monewment API Reference\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\\n")
        f.write("> **Base URL:** `http://localhost:8001`\\n\\n")
        
        f.write("---\\n\\n")
        
        # 인증 섹션
        f.write("## 🔐 Authentication\\n\\n")
        f.write("Most endpoints require JWT authentication.\\n\\n")
        f.write("```http\\n")
        f.write("Authorization: Bearer <your_jwt_token>\\n")
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        
        # 태그별로 그룹화
        grouped_apis = {}
        for api in api_list:
            tags = api.get('tags', ['General'])
            tag = tags[0] if tags else 'General'
            
            if tag not in grouped_apis:
                grouped_apis[tag] = []
            grouped_apis[tag].append(api)
        
        # 각 태그별로 문서 작성
        for tag, apis in sorted(grouped_apis.items()):
            f.write(f"## 📂 {tag}\\n\\n")
            
            for api in apis:
                path = api.get('path', '/unknown')
                methods = api.get('methods', ['GET'])
                name = api.get('name', 'Unknown')
                description = api.get('description', '설명 없음')
                
                for method in methods:
                    f.write(f"### `{method} {path}`\\n\\n")
                    f.write(f"**Description:** {description}\\n\\n")
                    
                    # 요청 예제
                    f.write("**Request Example:**\\n\\n")
                    f.write("```http\\n")
                    f.write(f"{method} {path} HTTP/1.1\\n")
                    f.write("Host: localhost:8001\\n")
                    f.write("Content-Type: application/json\\n")
                    
                    if method in ['POST', 'PUT', 'PATCH']:
                        f.write("\\n")
                        f.write(generate_request_body(path, method))
                    
                    f.write("```\\n\\n")
                    
                    # 응답 예제
                    f.write("**Response Example:**\\n\\n")
                    f.write("```json\\n")
                    f.write(generate_response_example(path, method))
                    f.write("```\\n\\n")
                    
                    f.write("---\\n\\n")
        
        f.write("*Generated by Monewment Auto-Doc System v4.0*\\n")
    
    return {
        'file': output_file,
        'endpoints_count': len(api_list)
    }

def generate_request_body(path, method):
    """경로에 따른 요청 본문 예제 생성"""
    
    if 'login' in path.lower():
        return '''{
  "email": "admin@example.com",
  "password": "secure_password"
}'''
    elif 'signup' in path.lower():
        return '''{
  "email": "user@example.com",
  "password": "secure_password",
  "org_id": 1
}'''
    elif 'cluster' in path.lower():
        return '''{
  "name": "Seoul-Cluster-1",
  "region": "kr-seoul-1",
  "cpu_capacity": 1000,
  "ram_capacity_gb": 4096,
  "gpu_capacity": 64
}'''
    elif 'approve' in path.lower():
        return '''{
  "org_id": 1,
  "cluster_id": 1,
  "quota_cpu": 20,
  "quota_ram_gb": 64,
  "quota_gpu": 2
}'''
    elif 'project' in path.lower():
        return '''{
  "org_id": 1,
  "project_name": "MyProject"
}'''
    else:
        return '{}'

def generate_response_example(path, method):
    """경로에 따른 응답 예제 생성"""
    
    if 'login' in path.lower():
        return '''{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  "token_type": "bearer",
  "user": {
    "id": 1,
    "email": "admin@example.com",
    "role": "ADMIN"
  }
}'''
    elif 'hierarchy' in path.lower():
        return '''{
  "hierarchy": [
    {
      "id": 1,
      "name": "Seoul-Cluster-1",
      "region": "kr-seoul-1",
      "status": "ACTIVE",
      "organizations": [...]
    }
  ]
}'''
    elif method == 'DELETE':
        return '''{
  "message": "Successfully deleted",
  "id": 1
}'''
    else:
        return '''{
  "message": "Success",
  "data": {}
}'''

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    output = os.path.join(root, "docs", "auto_generated")
    os.makedirs(output, exist_ok=True)
    
    result = generate_api_docs(root, output)
    print(f"✅ API 문서 생성 완료: {result}")
