"""
아키텍처 문서 생성기
시스템 아키텍처를 Mermaid 다이어그램과 AI 분석으로 문서화합니다.
"""

import os
import requests
from datetime import datetime

def get_api_key():
    """Gemini API 키 가져오기"""
    key = os.getenv("GEMINI_API_KEY")
    if key:
        return key.strip().strip('"').strip("'")
    
    root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    env_path = os.path.join(root_dir, ".env")
    
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                if "GEMINI_API_KEY" in line and "=" in line:
                    val = line.split("=", 1)[1].strip()
                    return val.strip('"').strip("'")
    return None

def generate_architecture_docs(root_dir, output_dir):
    """아키텍처 문서 생성"""
    
    output_file = os.path.join(output_dir, "ARCHITECTURE.md")
    
    # 시스템 구조 다이어그램
    system_diagram = generate_system_diagram()
    
    # AI 분석 요청
    ai_analysis = analyze_architecture_with_ai(root_dir)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 🏗️ Monewment System Architecture\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\\n")
        
        f.write("---\\n\\n")
        
        # 시스템 개요
        f.write("## 📋 System Overview\\n\\n")
        f.write("Monewment is a B2B SaaS platform for high-performance computing resources (GPU VMs) ")
        f.write("targeting AI researchers and game developers.\\n\\n")
        
        # 시스템 아키텍처 다이어그램
        f.write("## 🗺️ System Architecture Diagram\\n\\n")
        f.write("```mermaid\\n")
        f.write(system_diagram)
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        
        # 기술 스택
        f.write("## 🛠️ Technology Stack\\n\\n")
        f.write("### Backend\\n")
        f.write("- **Framework:** FastAPI (Python 3.12+)\\n")
        f.write("- **Database:** PostgreSQL 15\\n")
        f.write("- **ORM:** SQLAlchemy (Sync)\\n")
        f.write("- **Authentication:** JWT + Bcrypt\\n")
        f.write("- **Container Orchestration:** Kubernetes\\n")
        f.write("- **Virtualization:** KubeVirt\\n\\n")
        
        f.write("### Frontend\\n")
        f.write("- **Framework:** Next.js 16.1.1 (App Router)\\n")
        f.write("- **UI Library:** React 19\\n")
        f.write("- **Styling:** Tailwind CSS 4\\n")
        f.write("- **Language:** TypeScript\\n\\n")
        
        f.write("### Infrastructure\\n")
        f.write("- **Containerization:** Docker\\n")
        f.write("- **Orchestration:** Kubernetes (Local: Docker Desktop)\\n")
        f.write("- **Remote Access:** Apache Guacamole\\n\\n")
        
        f.write("---\\n\\n")
        
        # AI 분석
        f.write("## 🧠 AI Architecture Analysis\\n\\n")
        f.write(ai_analysis)
        f.write("\\n\\n")
        
        f.write("---\\n\\n")
        
        # 데이터 플로우
        f.write("## 🔄 Data Flow\\n\\n")
        f.write("```mermaid\\n")
        f.write(generate_data_flow_diagram())
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        f.write("*Generated by Monewment Auto-Doc System v4.0*\\n")
    
    return {
        'file': output_file
    }

def generate_system_diagram():
    """시스템 아키텍처 다이어그램 생성"""
    return """graph TB
    subgraph "Frontend Layer"
        UI[Next.js UI]
        Admin[Admin Dashboard]
    end
    
    subgraph "API Layer"
        API[FastAPI Backend]
        Auth[JWT Auth]
    end
    
    subgraph "Business Logic"
        Hierarchy[Hierarchy Manager]
        Billing[Billing Engine]
        VM[VM Manager]
    end
    
    subgraph "Data Layer"
        DB[(PostgreSQL)]
        Collector[System Collector]
    end
    
    subgraph "Infrastructure"
        K8s[Kubernetes]
        KubeVirt[KubeVirt]
        Guac[Guacamole]
    end
    
    UI --> API
    Admin --> API
    API --> Auth
    Auth --> Hierarchy
    Auth --> Billing
    Auth --> VM
    Hierarchy --> DB
    Billing --> DB
    VM --> K8s
    K8s --> KubeVirt
    KubeVirt --> Guac
    Collector --> DB
"""

def generate_data_flow_diagram():
    """데이터 플로우 다이어그램 생성"""
    return """sequenceDiagram
    participant User
    participant Frontend
    participant API
    participant Auth
    participant DB
    participant K8s
    
    User->>Frontend: Login Request
    Frontend->>API: POST /api/auth/login
    API->>Auth: Validate Credentials
    Auth->>DB: Query User
    DB-->>Auth: User Data
    Auth-->>API: JWT Token
    API-->>Frontend: Token + User Info
    Frontend-->>User: Dashboard
    
    User->>Frontend: Create VM
    Frontend->>API: POST /api/vms
    API->>Auth: Verify Token
    Auth-->>API: Authorized
    API->>DB: Create VM Record
    API->>K8s: Deploy VMI
    K8s-->>API: VMI Created
    API-->>Frontend: VM Info
    Frontend-->>User: VM Ready
"""

def analyze_architecture_with_ai(root_dir):
    """AI를 사용한 아키텍처 분석"""
    
    api_key = get_api_key()
    if not api_key:
        return "> ⚠️ Gemini API 키가 없어 AI 분석을 건너뜁니다."
    
    prompt = """Analyze the Monewment platform architecture and provide:
1. Key architectural patterns used
2. Scalability considerations
3. Security design principles
4. Potential bottlenecks
5. Recommended improvements

Focus on the 3-tier hierarchy (Cluster → Organization → Project) and the virtualization layer."""
    
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    
    try:
        res = requests.post(url, json=payload, timeout=30)
        if res.status_code == 200:
            return res.json()['candidates'][0]['content']['parts'][0]['text']
        else:
            return f"> ❌ AI 분석 실패 (코드 {res.status_code})"
    except Exception as e:
        return f"> ❌ AI 분석 오류: {str(e)}"

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    output = os.path.join(root, "docs", "auto_generated")
    os.makedirs(output, exist_ok=True)
    
    result = generate_architecture_docs(root, output)
    print(f"✅ 아키텍처 문서 생성 완료: {result}")
