"""
DB 스키마 문서 생성기
완전한 데이터베이스 스키마 문서를 ERD 다이어그램과 함께 생성합니다.
"""

import os
import sys
from datetime import datetime

# collector.py 사용 (DB 연결 실패 시 graceful degradation)
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def generate_db_schema_docs(root_dir, output_dir):
    """DB 스키마 문서 생성"""
    
    # DB 스키마 수집 (연결 실패 시 빈 리스트 반환)
    try:
        from src.collector import collector
        schema_info = collector.collect_db_schema()
    except Exception as e:
        print(f"⚠️ DB 연결 실패 (CI 환경에서는 정상): {str(e)}")
        schema_info = []
    
    # Mermaid ERD 다이어그램 생성
    erd_diagram = generate_erd_diagram(schema_info)
    
    # 문서 작성
    output_file = os.path.join(output_dir, "DB_SCHEMA.md")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 📊 Monewment Database Schema\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\\n")
        f.write("> **Auto-generated** by Monewment Documentation System v4.0\\n\\n")
        
        f.write("---\\n\\n")
        
        # ERD 다이어그램
        f.write("## 🗺️ Entity Relationship Diagram\\n\\n")
        f.write("```mermaid\\n")
        f.write(erd_diagram)
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        
        # 테이블 상세 정보
        f.write("## 📋 Table Details\\n\\n")
        
        if isinstance(schema_info, list) and len(schema_info) > 0:
            for table in schema_info:
                if 'error' in table:
                    continue
                    
                table_name = table.get('table_name', 'Unknown')
                columns = table.get('columns', [])
                
                f.write(f"### `{table_name}`\\n\\n")
                
                # 컬럼 테이블
                f.write("| Column | Type | Nullable | Primary Key | Description |\\n")
                f.write("|--------|------|----------|-------------|-------------|\\n")
                
                for col in columns:
                    name = col.get('name', 'N/A')
                    col_type = col.get('type', 'N/A')
                    nullable = '✅' if col.get('nullable', True) else '❌'
                    pk = '🔑' if col.get('primary_key', False) else ''
                    
                    f.write(f"| `{name}` | {col_type} | {nullable} | {pk} | |\\n")
                
                f.write("\\n")
        else:
            f.write("> ⚠️ DB 연결 실패 또는 테이블 없음\\n\\n")
        
        f.write("---\\n\\n")
        f.write("*Generated by Monewment Auto-Doc System v4.0*\\n")
    
    return {
        'file': output_file,
        'tables_count': len(schema_info) if isinstance(schema_info, list) else 0
    }

def generate_erd_diagram(schema_info):
    """Mermaid ERD 다이어그램 생성"""
    
    if not isinstance(schema_info, list) or len(schema_info) == 0:
        return "erDiagram\\n    NO_DATA\\n"
    
    diagram = "erDiagram\\n"
    
    # 관계 매핑 (간단한 버전)
    relationships = {
        'organizations': ['users', 'rooms', 'projects'],
        'projects': ['project_members', 'vm_instances'],
        'users': ['project_members'],
        'clusters': ['organizations']
    }
    
    # 테이블 정의
    for table in schema_info:
        if 'error' in table:
            continue
            
        table_name = table.get('table_name', 'Unknown').upper()
        columns = table.get('columns', [])
        
        diagram += f"    {table_name} {{\\n"
        
        for col in columns[:5]:  # 처음 5개 컬럼만
            name = col.get('name', 'N/A')
            col_type = col.get('type', 'N/A').split('(')[0]  # 타입 간소화
            pk = 'PK' if col.get('primary_key', False) else ''
            
            diagram += f"        {col_type} {name} {pk}\\n"
        
        diagram += "    }\\n"
    
    # 관계 정의
    for parent, children in relationships.items():
        parent_upper = parent.upper()
        for child in children:
            child_upper = child.upper()
            diagram += f"    {parent_upper} ||--o{{ {child_upper} : has\\n"
    
    return diagram

if __name__ == "__main__":
    # 테스트 실행
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    output = os.path.join(root, "docs", "auto_generated")
    os.makedirs(output, exist_ok=True)
    
    result = generate_db_schema_docs(root, output)
    print(f"✅ DB Schema 문서 생성 완료: {result}")
