"""
배포 가이드 생성기
Docker 및 Kubernetes 배포 가이드를 생성합니다.
"""

import os
from datetime import datetime

def generate_deployment_docs(root_dir, output_dir):
    """배포 가이드 생성"""
    
    output_file = os.path.join(output_dir, "DEPLOYMENT_GUIDE.md")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 🚢 Monewment Deployment Guide\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\\n")
        
        f.write("---\\n\\n")
        
        # 사전 요구사항
        f.write("## 📋 Prerequisites\\n\\n")
        f.write("- Docker Desktop (with Kubernetes enabled)\\n")
        f.write("- kubectl CLI\\n")
        f.write("- Python 3.12+\\n")
        f.write("- Node.js 18+\\n")
        f.write("- PostgreSQL 15\\n\\n")
        
        f.write("---\\n\\n")
        
        # 로컬 개발 환경
        f.write("## 💻 Local Development Setup\\n\\n")
        f.write("### 1. Clone Repository\\n\\n")
        f.write("```bash\\n")
        f.write("git clone https://github.com/abrosskr/Monewment.git\\n")
        f.write("cd Monewment\\n")
        f.write("```\\n\\n")
        
        f.write("### 2. Environment Variables\\n\\n")
        f.write("Create `.env` file:\\n\\n")
        f.write("```env\\n")
        f.write("DATABASE_URL=postgresql://postgres:postgres@localhost:5433/monewment\\n")
        f.write("GEMINI_API_KEY=your_api_key_here\\n")
        f.write("JWT_SECRET_KEY=your_secret_key_here\\n")
        f.write("```\\n\\n")
        
        f.write("### 3. Database Setup\\n\\n")
        f.write("```bash\\n")
        f.write("# Start PostgreSQL\\n")
        f.write("kubectl port-forward svc/main-db 5433:5432 -n default\\n\\n")
        f.write("# Run migrations\\n")
        f.write("python scripts/init_db.py\\n")
        f.write("```\\n\\n")
        
        f.write("### 4. Start Backend\\n\\n")
        f.write("```bash\\n")
        f.write("cd src\\n")
        f.write("pip install -r requirements.txt\\n")
        f.write("uvicorn main:app --reload --port 8001\\n")
        f.write("```\\n\\n")
        
        f.write("### 5. Start Frontend\\n\\n")
        f.write("```bash\\n")
        f.write("cd gui\\n")
        f.write("npm install\\n")
        f.write("npm run dev\\n")
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        
        # Docker 배포
        f.write("## 🐳 Docker Deployment\\n\\n")
        f.write("### Build Images\\n\\n")
        f.write("```bash\\n")
        f.write("# Backend\\n")
        f.write("docker build -t monewment-backend:latest -f Dockerfile.backend .\\n\\n")
        f.write("# Frontend\\n")
        f.write("docker build -t monewment-frontend:latest -f Dockerfile.frontend .\\n")
        f.write("```\\n\\n")
        
        f.write("### Run with Docker Compose\\n\\n")
        f.write("```bash\\n")
        f.write("docker-compose up -d\\n")
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        
        # Kubernetes 배포
        f.write("## ☸️ Kubernetes Deployment\\n\\n")
        f.write("### Apply Manifests\\n\\n")
        f.write("```bash\\n")
        f.write("# Database\\n")
        f.write("kubectl apply -f k8s/postgres-deployment.yml\\n\\n")
        f.write("# Backend\\n")
        f.write("kubectl apply -f k8s/backend-deployment.yml\\n\\n")
        f.write("# Frontend\\n")
        f.write("kubectl apply -f k8s/frontend-deployment.yml\\n")
        f.write("```\\n\\n")
        
        f.write("### Verify Deployment\\n\\n")
        f.write("```bash\\n")
        f.write("kubectl get pods\\n")
        f.write("kubectl get services\\n")
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        
        # 트러블슈팅
        f.write("## 🔧 Troubleshooting\\n\\n")
        f.write("### Database Connection Issues\\n\\n")
        f.write("```bash\\n")
        f.write("# Check PostgreSQL pod\\n")
        f.write("kubectl logs -l app=postgres\\n\\n")
        f.write("# Test connection\\n")
        f.write("kubectl exec -it <postgres-pod> -- psql -U postgres\\n")
        f.write("```\\n\\n")
        
        f.write("### Backend Not Starting\\n\\n")
        f.write("```bash\\n")
        f.write("# Check logs\\n")
        f.write("kubectl logs -l app=backend\\n\\n")
        f.write("# Verify environment variables\\n")
        f.write("kubectl describe pod <backend-pod>\\n")
        f.write("```\\n\\n")
        
        f.write("---\\n\\n")
        f.write("*Generated by Monewment Auto-Doc System v4.0*\\n")
    
    return {
        'file': output_file
    }

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    output = os.path.join(root, "docs", "deployment")
    os.makedirs(output, exist_ok=True)
    
    result = generate_deployment_docs(root, output)
    print(f"✅ 배포 가이드 생성 완료: {result}")
