"""
기능 명세서 생성기
프로젝트의 모든 함수와 클래스를 분석하여 기능 명세서를 생성합니다.
"""

import os
import ast
from datetime import datetime

def generate_function_spec(root_dir, output_dir):
    """기능 명세서 (FUNCTION.md) 생성"""
    
    output_file = os.path.join(output_dir, "FUNCTION.md")
    src_dir = os.path.join(root_dir, "src")
    
    if not os.path.exists(src_dir):
        return {'error': 'src directory not found'}
        
    specs = {} # file_path: [items]

    for root, _, files in os.walk(src_dir):
        for file in files:
            if file.endswith(".py") and file != "__init__.py":
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, root_dir)
                
                with open(file_path, 'r', encoding='utf-8') as f:
                    try:
                        tree = ast.parse(f.read())
                        items = []
                        
                        for node in ast.walk(tree):
                            if isinstance(node, ast.FunctionDef):
                                # 독립 함수 (글로벌 스코프)만 추출하거나, 필요시 클래스 메서드도 포함 가능
                                # 여기서는 최상위 함수만 먼저 본다고 가정 (또는 parent tracking 필요)
                                # 간단하게 모든 함수 노드를 수집하되, 이름으로 구분
                                
                                docstring = ast.get_docstring(node) or "설명 없음"
                                docstring = docstring.split('\n')[0] # 첫 줄만
                                
                                args = [arg.arg for arg in node.args.args]
                                signature = f"{node.name}({', '.join(args)})"
                                
                                items.append({
                                    'type': 'Function',
                                    'name': node.name,
                                    'signature': signature,
                                    'docstring': docstring,
                                    'lineno': node.lineno
                                })
                            elif isinstance(node, ast.ClassDef):
                                docstring = ast.get_docstring(node) or "설명 없음"
                                docstring = docstring.split('\n')[0]
                                
                                items.append({
                                    'type': 'Class',
                                    'name': node.name,
                                    'signature': f"class {node.name}",
                                    'docstring': docstring,
                                    'lineno': node.lineno
                                })
                        
                        if items:
                            items.sort(key=lambda x: x['lineno'])
                            specs[rel_path] = items
                            
                    except Exception as e:
                        print(f"Error parsing {file_path}: {e}")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 🧩 Functional Specification\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        for file_path, items in sorted(specs.items()):
            f.write(f"## 📄 {file_path}\n\n")
            
            f.write("| Type | Name | Signature | Description |\n")
            f.write("|:---:|:---|:---|:---|\n")
            
            for item in items:
                type_icon = "Ⓜ️" if item['type'] == 'Function' else "ⓒ"
                f.write(f"| {type_icon} {item['type']} | `{item['name']}` | `{item['signature']}` | {item['docstring']} |\n")
            
            f.write("\n---\n\n")
            
        f.write("*Generated by Monewment Auto-Doc System v5.0*\n")

    return {
        'file': output_file,
        'files_scanned': len(specs)
    }
