"""
프로젝트 구조 생성기
프로젝트의 디렉토리 구조를 트리 형태로 스캔하여 문서화합니다.
"""

import os

def generate_structure_docs(root_dir, output_dir):
    """프로젝트 구조 문서 생성"""
    
    output_file = os.path.join(output_dir, "STRUCTURE.md")
    
    # 제외할 디렉토리 및 파일
    exclude_dirs = {
        '.git', '.idea', '.vscode', '__pycache__', 'venv', 'env', 'node_modules', 
        '.next', 'dist', 'build', 'coverage', '.pytest_cache', 'site-packages',
        'Model', 'Network', 'Structure' # User specific exclusions if any
    }
    
    exclude_files = {
        '.DS_Store', 'Thumbs.db', '.gitignore', '.env', '.env.local'
    }

    def get_file_structure(path, prefix=""):
        structure_str = ""
        try:
            items = sorted(os.listdir(path))
            items = [i for i in items if i not in exclude_files and i not in exclude_dirs]
            
            # 디렉토리와 파일을 분리하여 정렬 (디렉토리 먼저)
            dirs = [i for i in items if os.path.isdir(os.path.join(path, i))]
            files = [i for i in items if os.path.isfile(os.path.join(path, i))]
            sorted_items = dirs + files
            
            for index, item in enumerate(sorted_items):
                full_path = os.path.join(path, item)
                is_last = (index == len(sorted_items) - 1)
                
                connector = "└── " if is_last else "├── "
                
                if os.path.isdir(full_path):
                    structure_str += f"{prefix}{connector}📂 {item}/\n"
                    extension = "    " if is_last else "│   "
                    structure_str += get_file_structure(full_path, prefix + extension)
                else:
                    structure_str += f"{prefix}{connector}📄 {item}\n"
                    
        except PermissionError:
            pass
            
        return structure_str

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# 📂 Project Structure Map\n\n")
        f.write(f"📦 {os.path.basename(root_dir)}\n")
        f.write(get_file_structure(root_dir))
        f.write("\n")
        f.write("*Generated by Monewment Auto-Doc System v5.0*\n")
    
    return {
        'file': output_file
    }
