"""
사용자 매뉴얼 생성기
Super Admin 및 Project Admin 매뉴얼을 생성합니다.
"""

import os
from datetime import datetime

def generate_user_manual(root_dir, output_dir):
    """사용자 매뉴얼 생성"""
    
    # Super Admin 매뉴얼
    admin_file = os.path.join(output_dir, "SUPER_ADMIN_MANUAL.md")
    
    with open(admin_file, 'w', encoding='utf-8') as f:
        f.write("# 👑 Super Admin Manual\n\n")
        f.write(f"> **Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 📋 Overview\\n\\n")
        f.write("Super Admin Console을 사용하여 전체 플랫폼을 관리하는 방법을 안내합니다.\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 🚀 Getting Started\\n\\n")
        f.write("### Accessing the Dashboard\\n\\n")
        f.write("1. Navigate to `http://localhost:3001/admin`\\n")
        f.write("2. Login with Super Admin credentials\\n")
        f.write("3. You will see the Super Admin Engine dashboard\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 🏗️ Managing Clusters\\n\\n")
        f.write("### Creating a New Cluster\\n\\n")
        f.write("1. Click **\"New Cluster Connection\"** button\\n")
        f.write("2. The system will create a cluster with default capacity:\\n")
        f.write("   - CPU: 1000 cores\\n")
        f.write("   - RAM: 4096 GB\\n")
        f.write("   - GPU: 64 units\\n")
        f.write("3. A success toast notification will appear\\n")
        f.write("4. The new cluster will appear in the hierarchy view\\n\\n")
        
        f.write("### Viewing Cluster Details\\n\\n")
        f.write("- Each cluster card shows:\\n")
        f.write("  - Cluster name\\n")
        f.write("  - Region (e.g., kr-seoul-1)\\n")
        f.write("  - Status (ACTIVE, MAINTENANCE, DOWN)\\n")
        f.write("  - Number of organizations\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 🏢 Managing Organizations\\n\\n")
        f.write("### Approving Organizations\\n\\n")
        f.write("1. Check the **\"Pending Approval\"** section\\n")
        f.write("2. Review organization details:\\n")
        f.write("   - Organization name\\n")
        f.write("   - Requested tier (Enterprise, Pro, etc.)\\n")
        f.write("   - Region preference\\n")
        f.write("3. Click **\"PROCEED APPROVAL\"** button\\n")
        f.write("4. Default quotas will be assigned:\\n")
        f.write("   - CPU: 20 cores\\n")
        f.write("   - RAM: 64 GB\\n")
        f.write("   - GPU: 2 units\\n")
        f.write("5. Organization status changes to ACTIVE\\n\\n")
        
        f.write("### Viewing Organization Hierarchy\\n\\n")
        f.write("1. Click on an organization card to expand\\n")
        f.write("2. View assigned quotas (CPU, RAM, GPU)\\n")
        f.write("3. See all projects under the organization\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 📦 Managing Projects\\n\\n")
        f.write("### Deploying a New Project\\n\\n")
        f.write("1. Expand an organization card\\n")
        f.write("2. Click **\"Deploy Project\"** button\\n")
        f.write("3. A new project will be created with:\\n")
        f.write("   - Random project name\\n")
        f.write("   - Physical folder structure\\n")
        f.write("   - Database record\\n")
        f.write("4. Project appears in the organization's project list\\n\\n")
        
        f.write("### Viewing Project Status\\n\\n")
        f.write("- Each project shows:\\n")
        f.write("  - Project name\\n")
        f.write("  - Node ID\\n")
        f.write("  - Status indicator (green = active)\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 📊 Platform Vitals\\n\\n")
        f.write("The right sidebar shows:\\n")
        f.write("- **Active Utilization**: Current resource usage percentage\\n")
        f.write("- **Revenue Today**: Daily revenue metrics\\n")
        f.write("- **VM Nodes**: Total number of active VMs\\n\\n")
        
        f.write("---\\n\\n")
        
        f.write("## 💡 Admin Guide\\n\\n")
        f.write("Click **\"Open Onboarding Guide\"** to view:\\n")
        f.write("1. How to connect new infrastructure\\n")
        f.write("2. Organization approval process\\n")
        f.write("3. Project deployment workflow\\n\\n")
        
        f.write("---\\n\\n")
        f.write("*Generated by Monewment Auto-Doc System v4.0*\\n")
    
    return {
        'file': admin_file
    }

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    output = os.path.join(root, "docs", "user_guide")
    os.makedirs(output, exist_ok=True)
    
    result = generate_user_manual(root, output)
    print(f"✅ 사용자 매뉴얼 생성 완료: {result}")
