"""Split PIM and SCM

Revision ID: 94a052db9574
Revises: 
Create Date: 2026-01-20 12:20:19.863013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '94a052db9574'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    op.drop_index(op.f('ix_food_types_name'), table_name='food_types')
    op.drop_table('food_types')
    op.drop_index(op.f('ix_places_biz_number'), table_name='places')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_table('places')
    op.drop_table('universal_records')
    op.drop_index(op.f('ix_standard_recipes_name'), table_name='standard_recipes')
    op.drop_table('standard_recipes')
    op.create_index(op.f('ix_product_master_std_sku'), 'product_master_std', ['sku'], unique=False)
    op.drop_column('product_master_std', 'manufacturing_type')
    op.create_index(op.f('ix_product_sourcing_std_product_gtin'), 'product_sourcing_std', ['product_gtin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sourcing_std_product_gtin'), table_name='product_sourcing_std')
    op.add_column('product_master_std', sa.Column('manufacturing_type', sa.VARCHAR(length=7), nullable=True))
    op.drop_index(op.f('ix_product_master_std_sku'), table_name='product_master_std')
    op.create_table('standard_recipes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('food_type_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('protein_modifier', sa.VARCHAR(), nullable=True),
    sa.Column('taste_modifier', sqlite.JSON(), nullable=True),
    sa.Column('standard_ingredients', sqlite.JSON(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['food_type_id'], ['food_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_recipes_name'), 'standard_recipes', ['name'], unique=False)
    op.create_table('universal_records',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('service_type', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=True),
    sa.Column('common_data', sqlite.JSON(), nullable=True),
    sa.Column('extra_info', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('biz_number', sa.VARCHAR(), nullable=True),
    sa.Column('owner_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('platform_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_index(op.f('ix_places_biz_number'), 'places', ['biz_number'], unique=False)
    op.create_table('food_types',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('base_material', sa.VARCHAR(), nullable=True),
    sa.Column('default_method', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('fixed_cost', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_types_name'), 'food_types', ['name'], unique=1)
    op.create_table('menus',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('place_id', sa.NUMERIC(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('standard_recipe_id', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['standard_recipe_id'], ['standard_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
