from fastapi import APIRouter, Depends, HTTPException, status
from typing import Dict, Any

# Mock Database imports (since crud/db logic wasn't fully generated by Squad)
# In production, import get_db, create_task_entry from database module
from app.schemas import TaskInput, TaskResponse, TaskStatus
from workers.tasks import process_data
from app.dependencies import authenticate_user

router = APIRouter(
    prefix="/tasks",
    tags=["Tasks"],
    dependencies=[Depends(authenticate_user)]
)

@router.post("/submit", response_model=TaskResponse, status_code=status.HTTP_202_ACCEPTED)
def submit_long_running_task(
    input_data: TaskInput,
    user_id: str = Depends(authenticate_user)
):
    """
    Submits a task to the Celery queue.
    """
    try:
        # 1. (Mock) Create DB Entry -> ID: "task_123"
        task_id = "task_123" 
        
        # 2. Submit to Celery
        # .delay() is the standard Celery method
        # We pass dict() because Celery likes primitives
        celery_task = process_data.delay(123, input_data.model_dump())
        
        return TaskResponse(
            task_id=str(celery_task.id),
            status="PENDING",
            message="Task submitted successfully."
        )

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Failed to submit task: {e}"
        )

@router.get("/{task_id}", response_model=TaskStatus)
def get_task_status(
    task_id: str,
    user_id: str = Depends(authenticate_user)
):
    """
    Retrieve task status.
    """
    # (Mock) Logic
    return TaskStatus(
        task_id=task_id,
        status="SUCCESS",
        result_data={"result": "mock_data"}
    )
