# ========================================================
# 🏁 Monewment Session End Script
# ========================================================
# 작업 세션 종료 시 자동으로 실행되는 스크립트
# - masterplan.md 업데이트
# - task.md 업데이트
# - 다음 할 일 목록 생성
# - 자동 커밋 및 푸시

param(
    [Parameter(Mandatory=$false)]
    [string]$SessionSummary = "작업 세션 완료"
)

$ErrorActionPreference = "Continue"
$root = "D:\projects\Monewment"
Set-Location $root

Write-Host "`n🏁 Monewment Session End - Auto Update" -ForegroundColor Cyan
Write-Host "=" * 60

# 1. 현재 Git 상태 확인
Write-Host "`n📊 [1/5] Checking current status..." -ForegroundColor Yellow
$gitStatus = git status --short
if ($gitStatus) {
    Write-Host "⚠️  Uncommitted changes detected:" -ForegroundColor Yellow
    Write-Host $gitStatus -ForegroundColor Gray
    
    $response = Read-Host "Commit these changes first? (Y/n)"
    if ($response -ne 'n') {
        .\scripts\smart_commit.ps1 -Message "chore: auto-save before session end"
    }
}

# 2. 최근 커밋 로그 수집
Write-Host "`n📝 [2/5] Collecting session activity..." -ForegroundColor Yellow
$recentCommits = git log --oneline --since="12 hours ago" --pretty=format:"%s"
$commitCount = ($recentCommits | Measure-Object).Count

Write-Host "Found $commitCount commits in this session" -ForegroundColor Gray

# 3. task.md 업데이트
Write-Host "`n✅ [3/5] Updating task.md..." -ForegroundColor Yellow
$taskFile = "C:\Users\abros\.gemini\antigravity\brain\c61561e6-bcdc-4506-a8b8-909c586d6c68\task.md"

if (Test-Path $taskFile) {
    $taskContent = Get-Content $taskFile -Raw
    
    # 완료된 항목 카운트
    $completedCount = ([regex]::Matches($taskContent, "\[x\]")).Count
    $totalCount = ([regex]::Matches($taskContent, "\[.\]")).Count
    $progress = [math]::Round(($completedCount / $totalCount) * 100, 1)
    
    Write-Host "  Progress: $completedCount/$totalCount tasks ($progress%)" -ForegroundColor Green
} else {
    Write-Host "  ⚠️  task.md not found" -ForegroundColor Yellow
}

# 4. masterplan.md 업데이트
Write-Host "`n📋 [4/5] Updating masterplan.md..." -ForegroundColor Yellow
$masterplanFile = "docs\masterplan.md"

if (Test-Path $masterplanFile) {
    $content = Get-Content $masterplanFile -Raw
    
    # 타임스탬프 추가
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $sessionNote = @"

---

## 📌 Session Update ($timestamp)

**Session Summary:** $SessionSummary

**Activity:**
- Commits: $commitCount
- Task Progress: $progress%

**Recent Changes:**
$($recentCommits | Select-Object -First 5 | ForEach-Object { "- $_" } | Out-String)

---
"@
    
    # 파일 끝에 추가
    Add-Content -Path $masterplanFile -Value $sessionNote
    Write-Host "  ✅ masterplan.md updated" -ForegroundColor Green
} else {
    Write-Host "  ⚠️  masterplan.md not found" -ForegroundColor Yellow
}

# 5. 다음 할 일 목록 생성
Write-Host "`n📝 [5/5] Generating next actions..." -ForegroundColor Yellow
$nextActionsFile = "docs\NEXT_ACTIONS.md"

$nextActions = @"
# 🎯 다음 할 일 (Next Actions)

> **Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
> **Last Session:** $SessionSummary

---

## 🔥 우선순위 높음 (High Priority)

### 1. 클러스터 및 프로젝트 삭제 기능 구현
- [ ] DELETE /api/admin/clusters/{id} API 구현
- [ ] DELETE /api/admin/projects/{id} API 구현
- [ ] Admin Dashboard에 삭제 버튼 UI 추가
- [ ] 삭제 확인 모달 구현

### 2. Project Admin Dashboard 개발
- [ ] 기본 레이아웃 설계
- [ ] 프로젝트 멤버 관리 UI
- [ ] VM 인스턴스 관리 UI
- [ ] 비용 모니터링 대시보드

---

## 📊 우선순위 중간 (Medium Priority)

### 3. Toss Payments 연동
- [ ] Sandbox 계정 생성
- [ ] 결제 API 엔드포인트 구현
- [ ] 결제 UI 컴포넌트 개발
- [ ] 테스트 결제 플로우 검증

### 4. 사용량 모니터링 시스템
- [ ] Usage Watchdog 알고리즘 설계
- [ ] 예산 초과 알림 시스템
- [ ] 실시간 사용량 대시보드

---

## 🔧 우선순위 낮음 (Low Priority)

### 5. 문서화 개선
- [ ] 환경 변수 문서 자동 생성
- [ ] 보안 정책 문서 작성
- [ ] 성능 최적화 가이드

### 6. 테스트 자동화
- [ ] E2E 테스트 (Playwright)
- [ ] API 통합 테스트
- [ ] 단위 테스트 커버리지 향상

---

## 📝 메모

- Smart Commit 스크립트 사용: ``.\scripts\smart_commit.ps1 -Message "your message"``
- 문서 생성: ``python scripts/generate_docs_v4.py``
- 실시간 감시: ``python scripts/watch_and_doc.py``

---

*Auto-generated by session_end.ps1*
"@

Set-Content -Path $nextActionsFile -Value $nextActions
Write-Host "  ✅ NEXT_ACTIONS.md created" -ForegroundColor Green

# 6. 자동 커밋
Write-Host "`n💾 Committing session updates..." -ForegroundColor Yellow
git add docs/masterplan.md docs/NEXT_ACTIONS.md 2>$null

$hasChanges = -not (git diff --quiet --staged 2>$null)
if ($hasChanges) {
    git commit -m "chore: session end - auto-update masterplan and next actions

Session: $SessionSummary
Commits: $commitCount
Progress: $progress%"
    
    git push origin feature/software-first-infra
    Write-Host "  ✅ Changes committed and pushed" -ForegroundColor Green
} else {
    Write-Host "  ℹ️  No changes to commit" -ForegroundColor Gray
}

# 완료 메시지
Write-Host "`n" + ("=" * 60)
Write-Host "🎉 Session End Complete!" -ForegroundColor Green
Write-Host ("=" * 60)
Write-Host "`nUpdated files:" -ForegroundColor Cyan
Write-Host "  📋 docs/masterplan.md" -ForegroundColor Gray
Write-Host "  🎯 docs/NEXT_ACTIONS.md" -ForegroundColor Gray
Write-Host "`nNext time you start, check NEXT_ACTIONS.md for your todo list!" -ForegroundColor Yellow
Write-Host "`n👋 See you next time!" -ForegroundColor Cyan
