# src/routers/tools.py
from fastapi import APIRouter, Body
from typing import List
import logging

# 라우터 정의 (이 파일은 'tools' 관련 기능만 담당함)
router = APIRouter(
    prefix="/tools",
    tags=["Tools & Utilities"]
)

logger = logging.getLogger()

@router.post("/generate-tree")
def generate_tree_api(file_paths: List[str] = Body(..., embed=True)):
    """
    파일 경로 리스트를 받아서 마크다운 트리로 변환
    """
    logger.info(f"Generating tree for {len(file_paths)} files")
    
    # 1. 트리 데이터 구조 만들기
    tree = {}
    for path in file_paths:
        parts = path.strip("/").split("/")
        current = tree
        for part in parts:
            current = current.setdefault(part, {})
            
    # 2. 마크다운 그리기 (재귀 함수)
    def draw_tree(current_tree, prefix=""):
        lines = []
        keys = sorted(current_tree.keys())
        for i, key in enumerate(keys):
            is_last = (i == len(keys) - 1)
            connector = "└── " if is_last else "├── "
            
            lines.append(f"{prefix}{connector}{key}")
            
            extension = "    " if is_last else "│   "
            if isinstance(current_tree[key], dict) and current_tree[key]:
                lines.extend(draw_tree(current_tree[key], prefix + extension))
        return lines

    markdown_output = "# 🏗️ Project Structure (Generated by Monewment API)\n\n```text\n"
    markdown_output += "\n".join(draw_tree(tree))
    markdown_output += "\n```\n"
    
    return {"markdown": markdown_output}