# app/services/isaac_bridge.py
from app.models.fis_protocol import FisFile, PhysicalProperties

class IsaacBridgeService:
    """
    [The Connector]
    Converts .fis Protocol Data -> NVIDIA Isaac Sim Python Script.
    Allows robot developers to "Import Physics" directly from our data.
    """

    @staticmethod
    def generate_isaac_script(fis_file: FisFile, primitives: list = None) -> str:
        """
        Generates a Python script that can be run inside NVIDIA Isaac Sim's Script Editor.
        This script applies the FIS physical properties to the current stage.
        
        Args:
            fis_file: The recipe protocol.
            primitives: List of VAcademy Primitives (e.g. [{"name":"Maillard", "friction_mod": 0.8}])
        """
        script_lines = [
            "# ---------------------------------------------------------",
            "# 🤖 Generated by Vendors FIS (Digital Taste Protocol)",
            f"# Recipe: {fis_file.metadata.recipe_id}",
            "# Target: NVIDIA Isaac Sim / Omniverse",
            "# Physics: Connected to V-Academy Neural Engine",
            "# ---------------------------------------------------------",
            "",
            "import omni.isaac.core.utils.prims as prim_utils",
            "from pxr import UsdPhysics, Gf, Sdf",
            "",
            "def apply_fis_physics(stage, prim_path, props):",
            "    # 1. Apply Rigid Body Physics (Mass, Friction)",
            "    # Note: In real sim, we would create a PhysicsMaterial",
            "    print(f'Applying FIS Physics to {prim_path}...')",
            "    print(f'   -> Friction: {props.get('friction', 0.5)}')",
            "    print(f'   -> Viscosity: {props.get('viscosity_cp', 'N/A')}')",
            "    pass",
            "",
            "# --- FIS Data Payload ---"
        ]

        # Convert Ingredients to Isaac Asset Definitions
        for name, props in fis_file.ingredients.items():
            # Defaults
            friction = 0.5
            viscosity = 1.0 # Water-like
            
            # 1. State Heuristics & File Logic
            if props.state == "Liquid":
                friction = 0.1
                viscosity = 1.0
            elif props.state == "Solid":
                friction = 0.8
                viscosity = 99999.0
            
            # Explicit Override from FIS File (Initial State)
            if props.viscosity_cp:
                viscosity = props.viscosity_cp
            
            # 2. V-Academy Overrides (The Brain Connection - Applies Intelligence)
            # If V-Academy detected "Starch_Slurry" -> Viscosity Up
            if primitives:
                for p in primitives:
                    # Very simple matching for prototype
                    p_name = p.get('name', '').lower()
                    if "reduction" in p_name or "thick" in p_name:
                         if props.state == "Liquid": 
                             viscosity = 500.0 # Sauce-like
                             script_lines.append(f"# 🧠 V-Academy Insight: Detected {p_name} -> Increased Viscosity (Overriding Initial: {props.viscosity_cp})")
                    if "sear" in p_name or "maillard" in p_name:
                         if props.state == "Solid":
                             friction = 0.9 # Rough surface

            item_block = [
                f"# Ingredient: {name}",
                f"# State: {props.state.value}",
                f"props_{name.lower()} = {{",
                f"    'friction': {friction},",
                f"    'viscosity_cp': {viscosity},",
                f"    'specific_heat': {props.specific_heat or 0},",
                "}",
                f"# TODO: Creates or gets prim at /World/Ingredients/{name}",
                f"# apply_fis_physics(stage, '/World/Ingredients/{name}', props_{name.lower()})",
                ""
            ]
            script_lines.extend(item_block)
            
        script_lines.append("# --- Cooking Sequence Simulation ---")
        script_lines.append("import asyncio")
        script_lines.append("async def simulate_recipe():")
        
        for cmd in fis_file.timeline:
            line = f"    print('[{cmd.sequence_no}] Executing {cmd.action.value} on {cmd.target} with params {cmd.params}')"
            script_lines.append(line)
            # Add sleep/wait simulation
            if "duration" in cmd.params:
                script_lines.append(f"    # await asyncio.sleep({cmd.params['duration']}) # Sim time")
        
        script_lines.append("")
        script_lines.append("# Run Simulation")
        script_lines.append("asyncio.ensure_future(simulate_recipe())")
        
        return "\n".join(script_lines)
